# lists

In [3]:
l = [1, 2, 3, 4] # indexing starts from 0

In [5]:
l[3]

4

In [6]:
"""negative indices
starts from 0, goes to L-1
but L-1 --> -1, L-2 --> -2 and so on"""
l[-1]

4

In [9]:
print(l[-2], l[2]) 
# L = 4, l[2] --> 3rd element, l[-2] --> 3rd element

3 3


In [11]:
# a list can store objects of different datatypes
l = [1, 'b', "asdadas", True, 1.0]

In [26]:
# create a list which starts from 0 and goes to 9
l = list(range(0, 10)) # most likely does not use a python loop

In [18]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
l = [i for i in range(0, 9)] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
# very slow python loop

In [22]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
l = [] # empty list
for i in range(0, 10):
    l.append(i)
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
# a list of odd numbers
odd = [i for i in range(1, 10, 2)] # values will be incremented by 2
odd

[1, 3, 5, 7, 9]

In [25]:
# a list of even numbers
even = [i for i in range(0, 10, 2)] # values will be incremented by 2
even

[0, 2, 4, 6, 8]

In [30]:
l = [1, 'b', "asdadas", True, 1.0]
l[1] = 'a' # the list l will be altered
print(l)
l[1] = 67
l

[1, 'a', 'asdadas', True, 1.0]


[1, 67, 'asdadas', True, 1.0]

# tuple

In [40]:
t = (1, "a", 1.0)
t[0] = 2 # tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [37]:
N = (90,)

In [39]:
N[0]

90

# numpy

In [43]:
import numpy as np

In [52]:
a = np.array([1, 2, 3, 4.0])
a

array([1., 2., 3., 4.])

In [53]:
a.dtype

dtype('float64')

In [51]:
a[2] = 9.1
a

array([1, 2, 9, 4])

In [57]:
a = np.array([0, 1, 2, 3, 4], dtype="float")
a

array([0., 1., 2., 3., 4.])

In [58]:
a.dtype

dtype('float64')

In [59]:
a = np.array([0, 1, 2, 3, 4], dtype="float32")
a.dtype

dtype('float32')

In [61]:
print("a:", a)
b = a # this does not work!!! be careful!
print("b:", b)
b[1] = 6
print("a:", a)
print("b:", b)

a: [0. 1. 2. 3. 4.]
b: [0. 1. 2. 3. 4.]
a: [0. 6. 2. 3. 4.]
b: [0. 6. 2. 3. 4.]


In [64]:
a = np.array([0, 1, 2, 3, 4], dtype="float32")
print("a:", a)
b = a.copy()
print("b:", b)

b[1] = 6

print("a:", a)
print("b:", b)

a: [0. 1. 2. 3. 4.]
b: [0. 1. 2. 3. 4.]
a: [0. 1. 2. 3. 4.]
b: [0. 6. 2. 3. 4.]


# file I/O

In [65]:
with open("a.txt", "w") as f:
    f.write("sdkfhskdhfhkdsf\n")

In [66]:
# not recommended
# f = open("a.txt", "w")
# f.write("asdadad")
# f.close()

In [72]:
with open("print_formatting.txt", "w") as f:
    f.write(f"{234.234:.8f}\t{10:d}\tstring\n")

In [73]:
# f"{C} {pos_x[0].8f} {pos_y[0].8f} {pos_z[0].8f}\n"